"""Strict Pydantic contracts at the API and model boundaries."""

from enum import StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from .security import contains_protected_trait_language, validate_bounded_json


class HiringOperation(StrEnum):
    REVIEW_CANDIDATE = "review_candidate"
    SEARCH_CANDIDATES = "search_candidates"


class HiringAgentRequest(BaseModel):
    """Direct JSON request accepted from the Next.js server adapter."""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    candidate_id: UUID | None = Field(
        default=None,
        alias="candidateId",
    )
    role_id: UUID | None = Field(default=None, alias="roleId")
    merchant_id: UUID = Field(alias="merchantId")
    operation: HiringOperation = HiringOperation.REVIEW_CANDIDATE
    request_id: UUID = Field(default_factory=uuid4, alias="requestId")
    instructions: str | None = Field(default=None, max_length=4_000)
    score: int | None = Field(default=None, ge=0, le=100)
    analysis: dict[str, Any] | None = None
    summary: str | None = Field(default=None, max_length=1_000)
    red_flags: list[Annotated[str, Field(max_length=500)]] | None = Field(
        default=None,
        alias="redFlags",
        max_length=50,
    )

    @field_validator("analysis")
    @classmethod
    def validate_analysis(cls, value: dict[str, Any] | None) -> dict[str, Any] | None:
        if value is None:
            return value
        validated = validate_bounded_json(value)
        if contains_protected_trait_language(str(validated)):
            raise ValueError("analysis cannot use protected characteristics")
        return validated

    @field_validator("summary")
    @classmethod
    def validate_summary(cls, value: str | None) -> str | None:
        if value and contains_protected_trait_language(value):
            raise ValueError("summary cannot use protected characteristics")
        return value

    @field_validator("red_flags")
    @classmethod
    def validate_red_flags(cls, value: list[str] | None) -> list[str] | None:
        if value and any(contains_protected_trait_language(flag) for flag in value):
            raise ValueError("redFlags cannot use protected characteristics")
        return value

    @model_validator(mode="after")
    def validate_operation_and_write(self) -> "HiringAgentRequest":
        if self.operation == HiringOperation.SEARCH_CANDIDATES:
            if self.candidate_id:
                raise ValueError("candidateId is not allowed for candidate search")
            if not self.instructions or not self.instructions.strip():
                raise ValueError("instructions are required for candidate search")

        write_requested = self.score is not None or self.analysis is not None
        if write_requested and not (
            self.candidate_id and self.role_id and self.score is not None and self.analysis
        ):
            raise ValueError(
                "a score update requires candidateId, roleId, score, and non-empty analysis"
            )
        return self

    @property
    def has_explicit_write(self) -> bool:
        """Only a complete, validated request can enter the guarded write node."""
        return bool(self.candidate_id and self.role_id and self.score is not None and self.analysis)


class HiringAgentAnalysis(BaseModel):
    """Bounded evidence fields generated by the model."""

    model_config = ConfigDict(extra="forbid")

    evidence: list[Annotated[str, Field(max_length=500)]] = Field(
        default_factory=list,
        max_length=20,
    )
    gaps: list[Annotated[str, Field(max_length=500)]] = Field(
        default_factory=list,
        max_length=20,
    )
    limitations: list[Annotated[str, Field(max_length=500)]] = Field(
        default_factory=list,
        max_length=20,
    )
    confidence: Literal["low", "medium", "high"] = "low"


class HiringAgentDraft(BaseModel):
    """Structured model output; executed tool names are deliberately excluded."""

    model_config = ConfigDict(extra="forbid")

    summary: str = Field(min_length=1, max_length=500)
    recommendation: str = Field(min_length=1, max_length=1_000)
    fit_score: int | None = Field(default=None, ge=0, le=100)
    analysis: HiringAgentAnalysis = Field(default_factory=HiringAgentAnalysis)


class HiringAgentOutput(HiringAgentDraft):
    """Stable JSON response returned through the Next.js compatibility route."""

    status: Literal["complete", "degraded", "refused"] = "complete"
    write_status: Literal["not_requested", "succeeded", "failed", "skipped"] = "not_requested"
    warnings: list[Annotated[str, Field(max_length=100)]] = Field(
        default_factory=list,
        max_length=20,
    )
    request_id: str = Field(min_length=1, max_length=64)
    tool_calls: list[str] = Field(default_factory=list)
